///////////////////////////////////////////////////////////
//  clsAgente.cs
//  Implementation of the Class clsAgente
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:42 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsAgente : ClaseBase {

		public clsAgente(){

		}

		~clsAgente(){

		}

		public override void Dispose(){

		}

	}//end clsAgente

}//end namespace SAFCore