///////////////////////////////////////////////////////////
//  clsBodega.cs
//  Implementation of the Class clsBodega
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:42 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsBodega : ClaseBase {

		public clsBodega(){

		}

		~clsBodega(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsBodega

}//end namespace SAFCore