///////////////////////////////////////////////////////////
//  clsCliente.cs
//  Implementation of the Class clsCliente
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsCliente : ClaseBase {

		private string m_celular;
		private string m_correo;
		private string m_direccion;
		private string m_identificacion;
		private string m_telefono;
		public SAFCore.clsCiudad m_clsCiudad;

		public clsCliente(){

		}

		~clsCliente(){

		}

		public override void Dispose(bool disposing){

		}

		public string Celular{
			get{
				return m_celular;
			}
			set{
				m_celular = value;
			}
		}

		public string Correo{
			get{
				return m_correo;
			}
			set{
				m_correo = value;
			}
		}

		public string Direccion{
			get{
				return m_direccion;
			}
			set{
				m_direccion = value;
			}
		}

		public string Identificacion{
			get{
				return m_identificacion;
			}
			set{
				m_identificacion = value;
			}
		}

		public string Telefono{
			get{
				return m_telefono;
			}
			set{
				m_telefono = value;
			}
		}

	}//end clsCliente

}//end namespace SAFCore