///////////////////////////////////////////////////////////
//  clsContrato.cs
//  Implementation of the Class clsContrato
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsContrato: ClaseBase {

		private bool m_anticipo;
		private bool m_camaracomercio;
		private bool m_cartapagare;
		private bool m_contratoalquiler;
		private bool m_deposito;
		private byte m_descuentoalquiler;
		private byte m_descuentomantenimiento;
		private byte m_descuentoreposicion;
		private byte m_descuentotransporte;
		private byte m_descuentoventa;
		private bool m_fotocopiacedula;
		private bool m_fotocopianit;
		private bool m_garantiascondiciones;
		private int m_id;
		private bool m_informacionbd;
		private bool m_letracambio;
		private bool m_pagare;
		private bool m_personajuridica;
		private bool m_personanatural;
		private byte m_porcentajeagente;
		public SAFCore.clsProyecto m_clsProyecto;
		public SAFCore.clsListaPrecio m_clsListaPrecio;

		public clsContrato(){

		}

		~clsContrato(){

		}

		public virtual void Dispose(){

		}

		public bool Anticipo{
			get{
				return m_anticipo;
			}
			set{
				m_anticipo = value;
			}
		}

		public bool CamaraComercio{
			get{
				return m_camaracomercio;
			}
			set{
				m_camaracomercio = value;
			}
		}

		public bool CcartaPagare{
			get{
				return m_cartapagare;
			}
			set{
				m_cartapagare = value;
			}
		}

		public bool ContratoAlquiler{
			get{
				return m_contratoalquiler;
			}
			set{
				m_contratoalquiler = value;
			}
		}

		public bool Deposito{
			get{
				return m_deposito;
			}
			set{
				m_deposito = value;
			}
		}

		public byte DescuentoAlquiler{
			get{
				return m_descuentoalquiler;
			}
			set{
				m_descuentoalquiler = value;
			}
		}

		public byte DescuentoMantenimiento{
			get{
				return m_descuentomantenimiento;
			}
			set{
				m_descuentomantenimiento = value;
			}
		}

		public byte DescuentoReposicion{
			get{
				return m_descuentoreposicion;
			}
			set{
				m_descuentoreposicion = value;
			}
		}

		public byte DescuentoTransporte{
			get{
				return m_descuentotransporte;
			}
			set{
				m_descuentotransporte = value;
			}
		}

		public byte DescuentoVenta{
			get{
				return m_descuentoventa;
			}
			set{
				m_descuentoventa = value;
			}
		}

		public bool FotoCopiaCedula{
			get{
				return m_fotocopiacedula;
			}
			set{
				m_fotocopiacedula = value;
			}
		}

		public bool FotoCopiaNit{
			get{
				return m_fotocopianit;
			}
			set{
				m_fotocopianit = value;
			}
		}

		public bool GarantiasCondiciones{
			get{
                return m_garantiascondiciones;
			}
			set{
                m_garantiascondiciones = value;
			}
		}

		public int Id{
			get{
				return m_id;
			}
			set{
				m_id = value;
			}
		}

		public bool InformacionBD{
			get{
				return m_informacionbd;
			}
			set{
				m_informacionbd = value;
			}
		}

		public bool LetraCambio{
			get{
				return m_letracambio;
			}
			set{
				m_letracambio = value;
			}
		}

		public bool Pagare{
			get{
				return m_pagare;
			}
			set{
				m_pagare = value;
			}
		}

		public bool PersonaJuridica{
			get{
				return m_personajuridica;
			}
			set{
				m_personajuridica = value;
			}
		}

		public bool PersonaNatural{
			get{
				return m_personanatural;
			}
			set{
				m_personanatural = value;
			}
		}

		public byte PorcentajeAgente{
			get{
				return m_porcentajeagente;
			}
			set{
				m_porcentajeagente = value;
			}
		}

	}//end clsContrato

}//end namespace SAFCore