///////////////////////////////////////////////////////////
//  clsCiudad.cs
//  Implementation of the Class clsCiudad
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsCiudad : ClaseBase {

		public clsCiudad(){

		}

		~clsCiudad(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsCiudad

}//end namespace SAFCore