///////////////////////////////////////////////////////////
//  clsCorte.cs
//  Implementation of the Class clsCorte
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace SAFCore {
	public class clsCorte:ClaseBase {

		private System.DateTime m_fecha;
		private int m_id;
		private int m_numero;
		public SAFCore.clsProyectoVenta m_clsProyectoVenta;
		public SAFCore.clsProyectoAlquiler m_clsProyectoAlquiler;

		public clsCorte(){

		}

		~clsCorte(){

		}

		public virtual void Dispose(){

		}

        public System.DateTime Fecha
        {
			get{
				return m_fecha;
			}
			set{
				m_fecha = value;
			}
		}
		
		public int Numero{
			get{
				return m_numero;
			}
			set{
				m_numero = value;
			}
		}

	}//end clsCorte

}//end namespace SAFCore