///////////////////////////////////////////////////////////
//  clsConductor.cs
//  Implementation of the Class clsConductor
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsConductor : ClaseBase {

		public clsConductor(){

		}

		~clsConductor(){

		}

		public override void Dispose(){

		}

	}//end clsConductor

}//end namespace SAFCore