///////////////////////////////////////////////////////////
//  clsDetalleDevolucion.cs
//  Implementation of the Class clsDetalleDevolucion
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleDevolucion : ClaseBaseDetalle {

		public SAFCore.clsDevolucion m_clsDevolucion;

		public clsDetalleDevolucion(){

		}

		~clsDetalleDevolucion(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleDevolucion

}//end namespace SAFCore