///////////////////////////////////////////////////////////
//  clsDetalleRepDevolucionServicio.cs
//  Implementation of the Class clsDetalleRepDevolucionServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleRepDevolucionServicio : ClaseBaseDetalle {

		public SAFCore.clsRepDevolucionServicio m_clsRepDevolucionServicio;

		public clsDetalleRepDevolucionServicio(){

		}

		~clsDetalleRepDevolucionServicio(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleRepDevolucionServicio

}//end namespace SAFCore