///////////////////////////////////////////////////////////
//  clsDetalleVenta.cs
//  Implementation of the Class clsDetalleVenta
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleVenta : ClaseBaseDetalle {

		public SAFCore.clsVenta m_clsVenta;

		public clsDetalleVenta(){

		}

		~clsDetalleVenta(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleVenta

}//end namespace SAFCore