///////////////////////////////////////////////////////////
//  clsDetalleCorte.cs
//  Implementation of the Class clsDetalleCorte
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleCorte : ClaseBaseDetalle {

		public SAFCore.clsCorte m_clsCorte;
		public SAFCore.clsProveedor m_clsProveedor;
		public SAFCore.clsRemision m_clsRemision;
		public SAFCore.clsFactura m_clsFactura;

		public clsDetalleCorte(){

		}

		~clsDetalleCorte(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleCorte

}//end namespace SAFCore