///////////////////////////////////////////////////////////
//  clsDetalleDevolucionServicio.cs
//  Implementation of the Class clsDetalleDevolucionServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleDevolucionServicio : ClaseBaseDetalle {

		public SAFCore.clsDevolucionServicio m_clsDevolucionServicio;

		public clsDetalleDevolucionServicio(){

		}

		~clsDetalleDevolucionServicio(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleDevolucionServicio

}//end namespace SAFCore