///////////////////////////////////////////////////////////
//  clsDetalleReposicion.cs
//  Implementation of the Class clsDetalleReposicion
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleReposicion : ClaseBaseDetalle {

		public SAFCore.clsReposicion m_clsReposicion;

		public clsDetalleReposicion(){

		}

		~clsDetalleReposicion(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleReposicion

}//end namespace SAFCore