///////////////////////////////////////////////////////////
//  clsDetalleRemision.cs
//  Implementation of the Class clsDetalleRemision
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleRemision : ClaseBaseDetalle {

		public SAFCore.clsRemision m_clsRemision;

		public clsDetalleRemision(){

		}

		~clsDetalleRemision(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleRemision

}//end namespace SAFCore