///////////////////////////////////////////////////////////
//  clsDocumento.cs
//  Implementation of the Class clsDocumento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDocumento : ClaseBaseDocumento {

		private string m_descripcion;
		private System.DateTime m_fecha;
		public SAFCore.clsTipoDocumento m_clsTipoDocumento;

		public clsDocumento(){

		}

		~clsDocumento(){

		}

		public override void Dispose(bool disposing){

		}

		public string Descripcion{
			get{
				return Descripcion;
			}
			set{
				Descripcion = value;
			}
		}

		public System.DateTime Fecha{
			get{
				return Fecha;
			}
			set{
				Fecha = value;
			}
		}

	}//end clsDocumento

}//end namespace SAFCore