///////////////////////////////////////////////////////////
//  clsDetalleDocumento.cs
//  Implementation of the Class clsDetalleDocumento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleDocumento : ClaseBaseDetalle {

		public new SAFCore.clsElemento m_clsElemento;
		public SAFCore.clsDocumento m_clsDocumento;

		public clsDetalleDocumento(){

		}

		~clsDetalleDocumento(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleDocumento

}//end namespace SAFCore