///////////////////////////////////////////////////////////
//  clsDetalleOrdenServicio.cs
//  Implementation of the Class clsDetalleOrdenServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleOrdenServicio : ClaseBaseDetalle {

		public SAFCore.clsOrdenServicio m_clsOrdenServicio;

		public clsDetalleOrdenServicio(){

		}

		~clsDetalleOrdenServicio(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleOrdenServicio

}//end namespace SAFCore