///////////////////////////////////////////////////////////
//  clsDevolucionServicio.cs
//  Implementation of the Class clsDevolucionServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDevolucionServicio : ClaseBaseDocumento {

		public SAFCore.clsProveedor m_clsProveedor;
		public SAFCore.clsDevolucion m_clsDevolucion;

		public clsDevolucionServicio(){

		}

		~clsDevolucionServicio(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDevolucionServicio

}//end namespace SAFCore