///////////////////////////////////////////////////////////
//  clsDetalleMantenimiento.cs
//  Implementation of the Class clsDetalleMantenimiento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:43 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsDetalleMantenimiento : ClaseBaseDetalle {

		private enuTipoMantenimiento m_tipomantenimiento;
		public SAFCore.clsMantenimiento m_clsMantenimiento;

		public clsDetalleMantenimiento(){

		}

		~clsDetalleMantenimiento(){

		}

		public override void Dispose(){

		}

        public enuTipoMantenimiento TipoMantenimiento
        {
			get{
				return m_tipomantenimiento;
			}
			set{
				m_tipomantenimiento = value;
			}
		}

	}//end clsDetalleMantenimiento

}//end namespace SAFCore