///////////////////////////////////////////////////////////
//  clsGrupoElemento.cs
//  Implementation of the Class clsGrupoElemento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsGrupoElemento : ClaseBase {

		public clsGrupoElemento(){

		}

		~clsGrupoElemento(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsGrupoElemento

}//end namespace SAFCore