///////////////////////////////////////////////////////////
//  clsListaPrecio.cs
//  Implementation of the Class clsListaPrecio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsListaPrecio : ClaseBase {

		public clsListaPrecio(){

		}

		~clsListaPrecio(){

		}

		public override void Dispose(){

		}

	}//end clsListaPrecio

}//end namespace SAFCore