///////////////////////////////////////////////////////////
//  clsMovimientoBodega.cs
//  Implementation of the Class clsMovimientoBodega
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace SAFCore {
	public class clsMovimientoBodega:ClaseBase {

		private int m_cantidad;
		private string m_documento;
		private int m_id;
		private string m_numero;
		private string m_operacion;
		public SAFCore.clsElemento m_clsElemento;
		public SAFCore.clsBodega m_clsBodega;

		public clsMovimientoBodega(){

		}

		~clsMovimientoBodega(){

		}

		public virtual void Dispose(){

		}

		public clsBodega BodegaDestino{
			get{
				return BodegaDestino;
			}
			set{
				BodegaDestino = value;
			}
		}

		public clsBodega BodegaOrigen{
			get{
				return BodegaOrigen;
			}
			set{
				BodegaOrigen = value;
			}
		}

		public int Cantidad{
			get{
				return Cantidad;
			}
			set{
				Cantidad = value;
			}
		}

		public string Documento{
			get{
				return Documento;
			}
			set{
				Documento = value;
			}
		}

		public clsElemento Elemento{
			get{
				return Elemento;
			}
			set{
				Elemento = value;
			}
		}

		public string Numero{
			get{
				return Numero;
			}
			set{
				Numero = value;
			}
		}

		public string Operacion{
			get{
				return Operacion;
			}
			set{
				Operacion = value;
			}
		}

	}//end clsMovimientoBodega

}//end namespace SAFCore