///////////////////////////////////////////////////////////
//  clsMantenimiento.cs
//  Implementation of the Class clsMantenimiento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsMantenimiento : ClaseBaseDocumento {

		public SAFCore.clsDevolucion m_clsDevolucion;

		public clsMantenimiento(){

		}

		~clsMantenimiento(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsMantenimiento

}//end namespace SAFCore