///////////////////////////////////////////////////////////
//  clsOrdenServicio.cs
//  Implementation of the Class clsOrdenServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsOrdenServicio : ClaseBaseDocumento {

		public SAFCore.clsRemision m_clsRemision;

		public clsOrdenServicio(){

		}

		~clsOrdenServicio(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsOrdenServicio

}//end namespace SAFCore