///////////////////////////////////////////////////////////
//  clsProyectoAlquiler.cs
//  Implementation of the Class clsProyectoAlquiler
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsProyectoAlquiler:ClaseBase {

		private int m_id;
		public SAFCore.clsProyecto m_clsProyecto;

		public clsProyectoAlquiler(){

		}

		~clsProyectoAlquiler(){

		}

		public virtual void Dispose(){

		}
		

	}//end clsProyectoAlquiler

}//end namespace SAFCore