///////////////////////////////////////////////////////////
//  clsProyectoVenta.cs
//  Implementation of the Class clsProyectoVenta
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:44 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsProyectoVenta {

		private int m_id;
		public SAFCore.clsProyecto m_clsProyecto;

		public clsProyectoVenta(){

		}

		~clsProyectoVenta(){

		}

		public virtual void Dispose(){

		}

		public int Id{
			get{
				return m_id;
			}
			set{
				m_id = value;
			}
		}

	}//end clsProyectoVenta

}//end namespace SAFCore