///////////////////////////////////////////////////////////
//  clsReposicion.cs
//  Implementation of the Class clsReposicion
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsReposicion : ClaseBaseDocumento {

		public SAFCore.clsDevolucion m_clsDevolucion;

		public clsReposicion(){

		}

		~clsReposicion(){

		}

		public override void Dispose(){

		}

	}//end clsReposicion

}//end namespace SAFCore