///////////////////////////////////////////////////////////
//  clsRepDevolucionServicio.cs
//  Implementation of the Class clsRepDevolucionServicio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsRepDevolucionServicio : ClaseBaseDocumento {

		public SAFCore.clsDevolucion m_clsDevolucion;

		public clsRepDevolucionServicio(){

		}

		~clsRepDevolucionServicio(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsRepDevolucionServicio

}//end namespace SAFCore