///////////////////////////////////////////////////////////
//  clsTipoDocumento.cs
//  Implementation of the Class clsTipoDocumento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsTipoDocumento : ClaseBase {

		private string m_operacion;

		public clsTipoDocumento(){

		}

		~clsTipoDocumento(){

		}

		public override void Dispose(){

		}

		public string Operacion{
			get{
				return Operacion;
			}
			set{
				Operacion = value;
			}
		}

	}//end clsTipoDocumento

}//end namespace SAFCore