///////////////////////////////////////////////////////////
//  clsUnidadMedida.cs
//  Implementation of the Class clsUnidadMedida
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsUnidadMedida : ClaseBase {

		public clsUnidadMedida(){

		}

		~clsUnidadMedida(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsUnidadMedida

}//end namespace SAFCore