///////////////////////////////////////////////////////////
//  clsVenta.cs
//  Implementation of the Class clsVenta
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore;
namespace SAFCore {
	public class clsVenta : ClaseBaseDocumento {

		public SAFCore.clsRemision m_clsRemision;

		public clsVenta(){

		}

		~clsVenta(){

		}

		public override void Dispose(){

		}

	}//end clsVenta

}//end namespace SAFCore