///////////////////////////////////////////////////////////
//  enuEstadoProyecto.cs
//  Implementation of the Class enuEstadoProyecto
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




namespace SAFCore {
	public enum enuEstadoProyecto : int {

	}//end enuEstadoProyecto

}//end namespace SAFCore