///////////////////////////////////////////////////////////
//  enuTipoMantenimiento.cs
//  Implementation of the Class enuTipoMantenimiento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




namespace SAFCore {
	public enum enuTipoMantenimiento : int {

	}//end enuTipoMantenimiento

}//end namespace SAFCore