///////////////////////////////////////////////////////////
//  enuTipoFactura.cs
//  Implementation of the Class enuTipoFactura
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:12:45 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




namespace SAFCore {
	public enum enuTipoFactura : int {

	}//end enuTipoFactura

}//end namespace SAFCore