///////////////////////////////////////////////////////////
//  clsAgenteDALC.cs
//  Implementation of the Class clsAgenteDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsAgenteDALC : EntidadBasica<clsAgente> {

		public clsAgenteDALC(){

		}

		~clsAgenteDALC(){

		}

		public override void Dispose(){

		}

	}//end clsAgenteDALC

}//end namespace DALC