///////////////////////////////////////////////////////////
//  clsBodegaDALC.cs
//  Implementation of the Class clsBodegaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsBodegaDALC : EntidadBase<clsBodega> {

		public clsBodegaDALC(){

		}

		~clsBodegaDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsBodegaDALC

}//end namespace DALC