///////////////////////////////////////////////////////////
//  clsContrato.cs
//  Implementation of the Class clsContrato
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsContratoDALC : Entidad<clsContrato> {

		public clsContratoDALC(){

		}

		~clsContratoDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsContrato obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsContrato obj)
        {

			return 0;
		}

	}//end clsContrato

}//end namespace DALC