///////////////////////////////////////////////////////////
//  clsCorteDALC.cs
//  Implementation of the Class clsCorteDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace SAFCore.DALC {
	internal class clsCorteDALC : Entidad<clsCorte> {

		public clsCorteDALC(){

		}

		~clsCorteDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsCorte obj)
        {

			return 0;
		}

	
		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsCorte obj)
        {

			return 0;
		}

	}//end clsCorteDALC

}//end namespace DALC