///////////////////////////////////////////////////////////
//  clsClienteDALC.cs
//  Implementation of the Class clsClienteDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsClienteDALC : EntidadBase<clsCliente> {

		public clsClienteDALC(){

		}

		~clsClienteDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsCliente obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Eliminar(clsCliente obj)
        {

			return 0;
		}

		
	}//end clsClienteDALC

}//end namespace DALC