///////////////////////////////////////////////////////////
//  clsConductorDALC.cs
//  Implementation of the Class clsConductorDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsConductorDALC : EntidadBasica<clsConductor> {

		public clsConductorDALC(){

		}

		~clsConductorDALC(){

		}

		public override void Dispose(){

		}

	}//end clsConductorDALC

}//end namespace DALC