///////////////////////////////////////////////////////////
//  clsCiudadDALC.cs
//  Implementation of the Class clsCiudadDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsCiudadDALC : EntidadBase<clsCiudad> {

		public clsCiudadDALC(){

		}

		~clsCiudadDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsCiudadDALC

}//end namespace DALC