///////////////////////////////////////////////////////////
//  clsDetalleListaPrecioDALC.cs
//  Implementation of the Class clsDetalleListaPrecioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleListaPrecioDALC : EntidadDetalle<clsDetalleListaPrecio> {

		public clsDetalleListaPrecioDALC(){

		}

		~clsDetalleListaPrecioDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleListaPrecioDALC

}//end namespace DALC