///////////////////////////////////////////////////////////
//  clsDetalleMantenimientoDALC.cs
//  Implementation of the Class clsDetalleMantenimientoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleMantenimientoDALC : EntidadDetalle<clsDetalleMantenimiento> {

		public clsDetalleMantenimientoDALC(){

		}

		~clsDetalleMantenimientoDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsDetalleMantenimiento obj)
        {

			return 0;
		}

		

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsDetalleMantenimiento obj)
        {

			return 0;
		}

	}//end clsDetalleMantenimientoDALC

}//end namespace DALC