///////////////////////////////////////////////////////////
//  clsDetalleFacturaDALC.cs
//  Implementation of the Class clsDetalleFacturaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleFacturaDALC : EntidadDetalle<clsDetalleFactura> {

		public clsDetalleFacturaDALC(){

		}

		~clsDetalleFacturaDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleFacturaDALC

}//end namespace DALC