///////////////////////////////////////////////////////////
//  clsDevolucionDALC.cs
//  Implementation of the Class clsDevolucionDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDevolucionDALC : EntidadDocumento<clsDevolucion> {

		public clsDevolucionDALC(){

		}

		~clsDevolucionDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsDevolucion obj)
        {

			return 0;
		}

		

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsDevolucion obj)
        {

			return 0;
		}

	}//end clsDevolucionDALC

}//end namespace DALC