///////////////////////////////////////////////////////////
//  clsDocumentoDALC.cs
//  Implementation of the Class clsDocumentoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDocumentoDALC : EntidadDocumento<clsDocumento> {

		public clsDocumentoDALC(){

		}

		~clsDocumentoDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsDocumento obj)
        {

			return 0;
		}


		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsDocumento obj)
        {

			return 0;
		}

	}//end clsDocumentoDALC

}//end namespace DALC