///////////////////////////////////////////////////////////
//  clsDetalleDevolucionServicioDALC.cs
//  Implementation of the Class clsDetalleDevolucionServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleDevolucionServicioDALC : EntidadDetalle<clsDetalleDevolucionServicio> {

		public clsDetalleDevolucionServicioDALC(){

		}

		~clsDetalleDevolucionServicioDALC(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleDevolucionServicioDALC

}//end namespace DALC