///////////////////////////////////////////////////////////
//  clsDetalleDocumentoDALC.cs
//  Implementation of the Class clsDetalleDocumentoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleDocumentoDALC : EntidadDetalle<clsDetalleDocumento> {

		public clsDetalleDocumentoDALC(){

		}

		~clsDetalleDocumentoDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleDocumentoDALC

}//end namespace DALC