///////////////////////////////////////////////////////////
//  clsDetalleRepDevolucionServicioDALC.cs
//  Implementation of the Class clsDetalleRepDevolucionServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleRepDevolucionServicioDALC : EntidadDetalle<clsDetalleRepDevolucionServicio> {

		public clsDetalleRepDevolucionServicioDALC(){

		}

		~clsDetalleRepDevolucionServicioDALC(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleRepDevolucionServicioDALC

}//end namespace DALC