///////////////////////////////////////////////////////////
//  clsDetalleOrdenServicioDALC.cs
//  Implementation of the Class clsDetalleOrdenServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleOrdenServicioDALC : EntidadDetalle<clsDetalleOrdenServicio> {

		public clsDetalleOrdenServicioDALC(){

		}

		~clsDetalleOrdenServicioDALC(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleOrdenServicioDALC

}//end namespace DALC