///////////////////////////////////////////////////////////
//  clsDetalleRemision.cs
//  Implementation of the Class clsDetalleRemision
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace SAFCore.DALC {
	internal class clsDetalleRemisionDALC : EntidadDetalle<clsDetalleRemision> {

		public clsDetalleRemisionDALC(){

		}

		~clsDetalleRemisionDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleRemision

}//end namespace DALC