///////////////////////////////////////////////////////////
//  clsDetalleDevolucionDALC.cs
//  Implementation of the Class clsDetalleDevolucionDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleDevolucionDALC : EntidadDetalle<clsDetalleDevolucion> {

		public clsDetalleDevolucionDALC(){

		}

		~clsDetalleDevolucionDALC(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleDevolucionDALC

}//end namespace DALC