///////////////////////////////////////////////////////////
//  clsDetalleReposicionDALC.cs
//  Implementation of the Class clsDetalleReposicionDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleReposicionDALC : EntidadDetalle<clsDetalleReposicion> {

		public clsDetalleReposicionDALC(){

		}

		~clsDetalleReposicionDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleReposicionDALC

}//end namespace DALC