///////////////////////////////////////////////////////////
//  clsDetalleCorteDALC.cs
//  Implementation of the Class clsDetalleCorteDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleCorteDALC : EntidadDetalle<clsDetalleCorte > {

		public clsDetalleCorteDALC(){

		}

		~clsDetalleCorteDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDetalleCorteDALC

}//end namespace DALC