///////////////////////////////////////////////////////////
//  clsDevolucionServicioDALC.cs
//  Implementation of the Class clsDevolucionServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDevolucionServicioDALC : EntidadDocumento<clsDevolucionServicio> {

		public clsDevolucionServicioDALC(){

		}

		~clsDevolucionServicioDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsDevolucionServicioDALC

}//end namespace DALC