///////////////////////////////////////////////////////////
//  clsDetalleVentaDALC.cs
//  Implementation of the Class clsDetalleVentaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsDetalleVentaDALC : EntidadDetalle<clsDetalleVenta> {

		public clsDetalleVentaDALC(){

		}

		~clsDetalleVentaDALC(){

		}

		public override void Dispose(){

		}

	}//end clsDetalleVentaDALC

}//end namespace DALC