///////////////////////////////////////////////////////////
//  clsElementoDALC.cs
//  Implementation of the Class clsElementoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsElementoDALC : EntidadBasica<clsElemento> {

		public clsElementoDALC(){

		}

		~clsElementoDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsElemento obj)
        {

			return 0;
		}

		
		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsElemento obj)
        {

			return 0;
		}

	}//end clsElementoDALC

}//end namespace DALC