///////////////////////////////////////////////////////////
//  clsFachadaClaseDetalle.cs
//  Implementation of the Class clsFachadaClaseDetalle
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace SAFCore.DALC {
	public class clsFachadaClaseDetalle {

		private clsDetalleDevolucionServicioDALC m_clsDetalleDevolucionServicioDALC;
        private clsDetalleRepDevolucionServicioDALC m_clsDetalleRepDevolucionServicioDALC;
        private clsDetalleMantenimientoDALC m_clsDetalleMantenimientoDALC;
        private clsDetalleReposicionDALC m_clsDetalleReposicionDALC;
        private clsDetalleDevolucionDALC m_clsDetalleDevolucionDALC;
        private clsDetalleDocumentoDALC m_clsDetalleDocumentoDALC;
        private clsDetalleCorteDALC m_clsDetalleCorteDALC;
        private clsDetalleFacturaDALC m_clsDetalleFacturaDALC;
        private clsDetalleListaPrecioDALC m_clsDetalleListaPrecioDALC;
        private clsDetalleOrdenServicioDALC m_clsDetalleOrdenServicioDALC;
        private clsDetalleVentaDALC m_clsDetalleVentaDALC;
        private clsDetalleRemisionDALC m_clsDetalleRemision;

		public clsFachadaClaseDetalle(){

		}

		~clsFachadaClaseDetalle(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleDocumento ConsultarDetalleCorte(int Id){

			return null;
		}

		public List<clsDetalleCorte> ConsultarDetalleCortes(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleDevolucion ConsultarDetalleDevolucion(int Id){

			return null;
		}

		public List<clsDetalleDevolucion> ConsultarDetalleDevoluciones(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleDevolucionServicio ConsultarDetalleDevolucionServicio(int Id){

			return null;
		}

		public List<clsDetalleDevolucionServicio> ConsultarDetalleDevolucionServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleDocumento ConsultarDetalleDocumento(int Id){

			return null;
		}

		public List<clsDetalleDocumento> ConsultarDetalleDocumentos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleFactura ConsultarDetalleFactura(int Id){

			return null;
		}

		public List<clsDetalleFactura> ConsultarDetalleFacturas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleListaPrecio ConsultarDetalleListaPrecio(int Id){

			return null;
		}

		public List<clsDetalleListaPrecio> ConsultarDetalleListaPrecios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleMantenimiento ConsultarDetalleMantenimiento(int Id){

			return null;
		}

		public List<clsDetalleMantenimiento> ConsultarDetalleMantenimientos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleOrdenServicio ConsultarDetalleOrdenServicio(int Id){

			return null;
		}

		public List<clsDetalleOrdenServicio> ConsultarDetalleOrdenServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleRemision ConsultarDetalleRemision(int Id){

			return null;
		}

		public List<clsDetalleRemision> ConsultarDetalleRemisiones(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleReposicion ConsultarDetalleReposicion(int Id){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDetalleVenta ConsultarDetalleVenta(int Id){

			return null;
		}

		public List<clsDetalleVenta> ConsultarDetalleVentas(){

			return null;
		}

		public List<clsDetalleRepDevolucionServicio> ConsultarRepDetalleDevolucionesServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
        public clsDetalleRepDevolucionServicio ConsultarRepDetalleDevolucionServicio(int Id)
        {

			return null;
		}

		public List<clsDetalleReposicion> ConsutlarDetalleReposiciones(){

			return null;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleCortes(clsDetalleCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleDevolucion(clsDetalleDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleDevolucionServicio(clsDetalleDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleDocumento(clsDetalleDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleFactura(clsDetalleFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleListaPrecio(clsDetalleListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleMantenimiento(clsDetalleMantenimiento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleOrdenServicio(clsDetalleOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleRemision(clsDetalleRemision Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleReposicion(clsDetalleReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDetalleVenta(clsDetalleVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarRepDetalleDevolucionServicio(clsDetalleRepDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleCortes(clsDetalleCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleDevolucion(clsDetalleDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleDevolucionServicio(clsDetalleDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleDocumento(clsDetalleDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleFactura(clsDetalleFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleListaPrecio(clsDetalleListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleMantenimiento(clsDetalleMantenimiento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleOrdenServicio(clsDetalleOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleRemision(clsDetalleRemision Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleReposicion(clsDetalleReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDetalleVenta(clsDetalleVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarRepDetalleDevolucionServicio(clsDetalleRepDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleCortes(clsDetalleCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleDevolucion(clsDetalleDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleDevolucionServicio(clsDetalleDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleDocumento(clsDetalleDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleFactura(clsDetalleFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleListaPrecio(clsDetalleListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleMantenimiento(clsDetalleMantenimiento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleOrdenServicio(clsDetalleOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleRemision(clsDetalleRemision Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleReposicion(clsDetalleReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDetalleVenta(clsDetalleVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarRepDetalleDevolucionServicio(clsDetalleRepDevolucionServicio Obj){

			return 0;
		}

	}//end clsFachadaClaseDetalle

}//end namespace DALC