///////////////////////////////////////////////////////////
//  clsFachadaClaseDocumento.cs
//  Implementation of the Class clsFachadaClaseDocumento
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


using System.Collections.Generic;
namespace SAFCore.DALC {
	public class clsFachadaClaseDocumento {

		private clsDevolucionDALC m_clsDevolucionDALC;
        private clsDevolucionServicioDALC m_clsDevolucionServicioDALC;
        private clsRepDevolucionServicioDALC m_clsRepDevolucionServicioDALC;
        private clsMantenimientoDALC m_clsMantenimientoDALC;
        private clsReposicionDALC m_clsReposicionDALC;
        private clsDocumentoDALC m_clsDocumentoDALC;
        private clsRemisionDALC m_clsRemisionDALC;
        private clsFacturaDALC m_clsFacturaDALC;
        private clsOrdenServicioDALC m_clsOrdenServicioDALC;
        private clsVentaDALC m_clsVentaDALC;

		public clsFachadaClaseDocumento(){

		}

		~clsFachadaClaseDocumento(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Id"></param>
		public clsDevolucion ConsultarDevolucion(int Id){

			return null;
		}

		public List<clsDevolucion> ConsultarDevoluciones(){

			return null;
		}

		public List<clsDevolucionServicio> ConsultarDevolucionServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDocumento ConsultarDocumento(int Id){

			return null;
		}

		public List<clsDocumento> ConsultarDocumentos(){

			return null;
		}

		public List<clsFactura> ConsultarFacturas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsMantenimiento ConsultarMantenimiento(int Id){

			return null;
		}

		public List<clsMantenimiento> ConsultarMantenimientos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsOrdenServicio ConsultarOrdenServicio(int Id){

			return null;
		}

		public List<clsOrdenServicio> ConsultarOrdenServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsRepDevolucionServicio ConsultarRepDevolucionServicio(int Id){

			return null;
		}

		public List<clsRepDevolucionServicio> ConsultarRepDevolucionServicios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsReposicion ConsultarReposicion(int Id){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsVenta ConsultarVenta(int Id){

			return null;
		}

		public List<clsVenta> ConsultarVentas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsDevolucionServicio ConsutlarDevolucionServicio(int Id){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsFactura ConsutlarFactura(int Id){

			return null;
		}

		public List<clsReposicion> ConsutlarReposiciones(){

			return null;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDevolucion(clsDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDevolucionServicio(clsDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarDocumento(clsDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarFactura(clsFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarMantenimiento(clsMantenimiento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarOrdenServicio(clsOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarRepDevolucionServicio(clsRepDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarReposicion(clsReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarVenta(clsVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDevolucion(clsDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDevolucionServicio(clsDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarDocumento(clsDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarFactura(clsFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarOrdenServicio(clsOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarRepDevolucionServicio(clsRepDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarReposicion(clsReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarVenta(clsVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDevolucion(clsDevolucion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDevolucionServicio(clsDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarDocumento(clsDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarFactura(clsFactura Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarMantenimiento(clsMantenimiento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarOrdenServicio(clsOrdenServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarRepDevolucionServicio(clsRepDevolucionServicio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarReposicion(clsReposicion Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarVenta(clsVenta Obj){

			return 0;
		}

	}//end clsFachadaClaseDocumento

}//end namespace DALC