///////////////////////////////////////////////////////////
//  clsFachadaClaseBase.cs
//  Implementation of the Class clsFachadaClaseBase
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:22 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace SAFCore.DALC {
	public class clsFachadaClaseBase {

		private clsListaPrecioDALC m_clsListaPrecioDALC;
        private clsClienteDALC m_clsClienteDALC;
        private clsCiudadDALC m_clsCiudadDALC;
        private clsBodegaDALC m_clsBodegaDALC;
        private clsTipoDocumentoDALC m_clsTipoDocumentoDALC;
        private clsElementoDALC m_clsElementoDALC;
        private clsGrupoElementoDALC m_clsGrupoElementoDALC;
        private clsUnidadMedidaDALC m_clsUnidadMedidaDALC;
        private clsConductorDALC m_clsConductorDALC;
        private clsProveedorDALC m_clsProveedorDALC;
        private clsProyectoDALC m_clsProyectoDALC;
        private clsAgenteDALC m_clsAgenteDALC;

		public clsFachadaClaseBase(){

		}

		~clsFachadaClaseBase(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Id"></param>
		public clsAgente ConsultarAgente(int Id){

			return null;
		}

		public List<clsAgente> ConsultarAgentes(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public SAFCore.clsBodega ConsultarBodega(int Id){

			return null;
		}

		public List<clsBodega> ConsultarBodegas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsCiudad ConsultarCiudad(int Id){

			return null;
		}

		public List<clsCiudad> ConsultarCiudades(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsCliente ConsultarCliente(int Id){

			return null;
		}

		public List<clsCliente> ConsultarClientes(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsConductor ConsultarConductor(int Id){

			return null;
		}

		public List<clsConductor> ConsultarConductores(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsElemento ConsultarElemento(int Id){

			return null;
		}

		public List<clsElemento> ConsultarElementos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsGrupoElemento ConsultarGrupoElemento(int Id){

			return null;
		}

		public List<clsGrupoElemento> ConsultarGruposElementos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsListaPrecio ConsultarListaPrecio(int Id){

			return null;
		}

		public List<clsListaPrecio> ConsultarListaPrecios(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsProveedor ConsultarProveedor(int Id){

			return null;
		}

		public List<clsProveedor> ConsultarProveedores(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsProyecto ConsultarProyecto(int Id){

			return null;
		}

		public List<clsProyecto> ConsultarProyectos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsTipoDocumento ConsultarTipoDocumento(int Id){

			return null;
		}

		public List<clsTipoDocumento> ConsultarTiposDocumentos(){

			return null;
		}

		public List<clsUnidadMedida> ConsultarUnidadesMedidas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsUnidadMedida ConsultarUnidadMedida(int Id){

			return null;
		}

		/// 
		/// <param name="Obj"></param>
		public int EdiarBodega(clsBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarAgente(clsAgente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarCiudad(clsCiudad Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarCliente(clsCliente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarConductor(clsConductor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarElemento(clsElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarGrupoElemento(clsGrupoElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarListaPrecio(clsListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarProveedor(clsProveedor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarProyecto(clsProyecto Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarTipoDocumento(clsTipoDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarUnidadMedida(clsUnidadMedida Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarAgente(clsAgente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarBodega(clsBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarCiudad(clsCiudad Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarCliente(clsCliente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarConductor(clsConductor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarElemento(clsElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarGrupoElemento(clsGrupoElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarListaPrecio(clsListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarProveedor(clsProveedor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarProyecto(clsProyecto Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarTipoDocumento(clsTipoDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarUnidadMedida(clsUnidadMedida Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarAgente(clsAgente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarBodega(clsBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarCiudad(clsCiudad Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarCliente(clsCliente Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarConductor(clsConductor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarElemento(clsElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarGrupoElemento(clsGrupoElemento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarListaPrecio(clsListaPrecio Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarProveedor(clsProveedor Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarProyecto(clsProyecto Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarTipoDocumento(clsTipoDocumento Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarUnidadMedida(clsUnidadMedida Obj){

			return 0;
		}

	}//end clsFachadaClaseBase

	

}//end namespace DALC