///////////////////////////////////////////////////////////
//  clsFachadaSAF.cs
//  Implementation of the Class clsFachadaSAF
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:23 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace SAFCore.DALC {
	public class clsFachadaSAF {

		private clsMovimientoBodegaDALC m_clsMovimientoBodegaDALC;
        private clsProyectoAlquilerDALC m_clsProyectoAlquilerDALC;
        private clsProyectoVentaDALC m_clsProyectoVentaDALC;
        private clsCorteDALC m_clsCorteDALC;
        private clsContratoDALC m_clsContrato;

		public clsFachadaSAF(){

		}

		~clsFachadaSAF(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Id"></param>
		public clsContrato ConsultarContrato(int Id){

			return null;
		}

		public List<clsContrato> ConsultarContratos(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsCorte ConsultarCorte(int Id){

			return null;
		}

		public List<clsCorte> ConsultarCortes(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsMovimientoBodega ConsultarMovimientoBodega(int Id){

			return null;
		}

		public List<clsMovimientoBodega> ConsultarMovimientoBodegas(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsProyectoAlquiler ConsultarProyectoAlquiler(int Id){

			return null;
		}

		public List<clsProyectoAlquiler> ConsultarProyectoAlquileres(){

			return null;
		}

		/// 
		/// <param name="Id"></param>
		public clsProyectoVenta ConsultarProyectoVenta(int Id){

			return null;
		}

		public List<clsProyectoVenta> ConsultarProyectoVentas(){

			return null;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarContrato(clsContrato Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarCorte(clsCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarMovimientoBodega(clsMovimientoBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarProyectoAlquiler(clsProyectoAlquiler Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EditarProyectoVenta(clsProyectoVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarContrato(clsContrato Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarCorte(clsCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarMovimientoBodega(clsMovimientoBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarProyectoAlquiler(clsProyectoAlquiler Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int EliminarProyectoVenta(clsProyectoVenta Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarContrato(clsContrato Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarCorte(clsCorte Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarMovimientoBodega(clsMovimientoBodega Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarProyectoAlquiler(clsProyectoAlquiler Obj){

			return 0;
		}

		/// 
		/// <param name="Obj"></param>
		public int InsertarProyectoVenta(clsProyectoVenta Obj){

			return 0;
		}

	}//end clsFachadaSAF

}//end namespace DALC