///////////////////////////////////////////////////////////
//  clsFacturaDALC.cs
//  Implementation of the Class clsFacturaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace SAFCore.DALC {
	internal class clsFacturaDALC : EntidadDocumento<clsFactura> {

		public clsFacturaDALC(){

		}

		~clsFacturaDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsFactura obj)
        {

			return 0;
		}

		
		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsFactura obj)
        {

			return 0;
		}

	}//end clsFacturaDALC

}//end namespace DALC