///////////////////////////////////////////////////////////
//  clsGrupoElementoDALC.cs
//  Implementation of the Class clsGrupoElementoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsGrupoElementoDALC : EntidadBase<clsGrupoElemento> {

		public clsGrupoElementoDALC(){

		}

		~clsGrupoElementoDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsGrupoElementoDALC

}//end namespace DALC