///////////////////////////////////////////////////////////
//  clsListaPrecioDALC.cs
//  Implementation of the Class clsListaPrecioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsListaPrecioDALC : EntidadBase<clsListaPrecio> {

		public clsListaPrecioDALC(){

		}

		~clsListaPrecioDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsListaPrecioDALC

}//end namespace DALC