///////////////////////////////////////////////////////////
//  clsMovimientoBodegaDALC.cs
//  Implementation of the Class clsMovimientoBodegaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsMovimientoBodegaDALC : Entidad<clsMovimientoBodega> {

		public clsMovimientoBodegaDALC(){

		}

		~clsMovimientoBodegaDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsMovimientoBodega obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsMovimientoBodega obj)
        {

			return 0;
		}

	}//end clsMovimientoBodegaDALC

}//end namespace DALC