///////////////////////////////////////////////////////////
//  clsMantenimientoDALC.cs
//  Implementation of the Class clsMantenimientoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsMantenimientoDALC : EntidadDocumento<clsMantenimiento> {

		public clsMantenimientoDALC(){

		}

		~clsMantenimientoDALC(){

		}

		public override void Dispose(){

		}

	}//end clsMantenimientoDALC

}//end namespace DALC