///////////////////////////////////////////////////////////
//  clsOrdenServicioDALC.cs
//  Implementation of the Class clsOrdenServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsOrdenServicioDALC : EntidadDocumento<clsOrdenServicio> {

		public clsOrdenServicioDALC(){

		}

		~clsOrdenServicioDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsOrdenServicioDALC

}//end namespace DALC