///////////////////////////////////////////////////////////
//  clsProveedorDALC.cs
//  Implementation of the Class clsProveedorDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsProveedorDALC : EntidadBasica<clsProveedor> {

		public clsProveedorDALC(){

		}

		~clsProveedorDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsProveedor obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsProveedor obj)
        {

			return 0;
		}

	}//end clsProveedorDALC

}//end namespace DALC