///////////////////////////////////////////////////////////
//  clsProyectoDALC.cs
//  Implementation of the Class clsProyectoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsProyectoDALC : EntidadBase<clsProyecto> {

		public clsProyectoDALC(){

		}

		~clsProyectoDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsProyecto obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Eliminar(clsProyecto obj)
        {

			return 0;
		}

		

	}//end clsProyectoDALC

}//end namespace DALC