///////////////////////////////////////////////////////////
//  clsProyectoAlquilerDALC.cs
//  Implementation of the Class clsProyectoAlquilerDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:24 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsProyectoAlquilerDALC : Entidad<clsProyectoAlquiler> {

		public clsProyectoAlquilerDALC(){

		}

		~clsProyectoAlquilerDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsProyectoAlquiler obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsProyectoAlquiler obj)
        {

			return 0;
		}

	}//end clsProyectoAlquilerDALC

}//end namespace DALC