///////////////////////////////////////////////////////////
//  clsProyectoVentaDALC.cs
//  Implementation of the Class clsProyectoVentaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsProyectoVentaDALC : Entidad<clsProyecto> {

		public clsProyectoVentaDALC(){

		}

		~clsProyectoVentaDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsProyecto obj)
        {

			return 0;
		}
		
		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsProyecto obj)
        {

			return 0;
		}

	}//end clsProyectoVentaDALC

}//end namespace DALC