///////////////////////////////////////////////////////////
//  clsRepDevolucionServicioDALC.cs
//  Implementation of the Class clsRepDevolucionServicioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsRepDevolucionServicioDALC : EntidadDocumento<clsRepDevolucionServicio> {

		public clsRepDevolucionServicioDALC(){

		}

		~clsRepDevolucionServicioDALC(){

		}

		public override void Dispose(){

		}

	}//end clsRepDevolucionServicioDALC

}//end namespace DALC