///////////////////////////////////////////////////////////
//  clsRemisionDALC.cs
//  Implementation of the Class clsRemisionDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace SAFCore.DALC {
	internal class clsRemisionDALC : EntidadDocumento<clsRemision> {

		public clsRemisionDALC(){

		}

		~clsRemisionDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
		internal override int Editar(clsRemision obj){

			return 0;
		}

		
		/// 
		/// <param name="obj"></param>
		internal override int Insertar(clsRemision obj){

			return 0;
		}

	}//end clsRemisionDALC

}//end namespace DALC