///////////////////////////////////////////////////////////
//  clsReposicionDALC.cs
//  Implementation of the Class clsReposicionDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsReposicionDALC : EntidadDocumento<clsReposicion> {

		public clsReposicionDALC(){

		}

		~clsReposicionDALC(){

		}

		public override void Dispose(){

		}

	}//end clsReposicionDALC

}//end namespace DALC