///////////////////////////////////////////////////////////
//  clsTipoDocumentoDALC.cs
//  Implementation of the Class clsTipoDocumentoDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsTipoDocumentoDALC : EntidadBase<clsTipoDocumento> {

		public clsTipoDocumentoDALC(){

		}

		~clsTipoDocumentoDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        internal override int Editar(clsTipoDocumento obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal override int Insertar(clsTipoDocumento obj)
        {

			return 0;
		}

	}//end clsTipoDocumentoDALC

}//end namespace DALC