///////////////////////////////////////////////////////////
//  clsUnidadMedidaDALC.cs
//  Implementation of the Class clsUnidadMedidaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using SAFCore.DALC;
namespace SAFCore.DALC {
	internal class clsUnidadMedidaDALC : EntidadBase<clsUnidadMedida> {

		public clsUnidadMedidaDALC(){

		}

		~clsUnidadMedidaDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsUnidadMedidaDALC

}//end namespace DALC