///////////////////////////////////////////////////////////
//  clsVentaDALC.cs
//  Implementation of the Class clsVentaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace SAFCore.DALC {
	internal class clsVentaDALC : EntidadDocumento<clsVenta> {

		public clsVentaDALC(){

		}

		~clsVentaDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsVentaDALC

}//end namespace DALC