///////////////////////////////////////////////////////////
//  EntidadBasica.cs
//  Implementation of the Class EntidadBasica
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 04:57:25 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Datos;

namespace SAFCore.DALC {

    internal abstract class EntidadBasica<T> where T : ClaseBase, new()
	{
		private Comandos m_ejecutor_base_datos;
		private string m_nombre_procedimiento;



		~EntidadBasica(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="ejecutorBaseDatos"></param>
		public EntidadBasica(Comandos ejecutorBaseDatos){

		}

		public EntidadBasica(){

		}

		/// 
		/// <param name="Id"></param>
        internal virtual T Consultar(int Id)
        {

			return null;
		}

		internal List<T> ConsultarTodos(){

			return null;
		}

		/// 
		/// <param name="obj"></param>
        internal virtual int Editar(T obj)
        {

			return 0;
		}

		public Comandos Ejecutor_Base_Datos{
			get{
				return m_ejecutor_base_datos;
			}
			set{
				m_ejecutor_base_datos = value;
			}
		}

		/// 
		/// <param name="obj"></param>
        internal virtual int Eliminar(T obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        internal virtual int Insertar(T obj)
        {

			return 0;
		}

		public string Nombre_Procedimiento{
			get{
				return m_nombre_procedimiento;
			}
			set{
				m_nombre_procedimiento = value;
			}
		}

	}//end EntidadBasica

}//end namespace DALC