///////////////////////////////////////////////////////////
//  ClaseBase.cs
//  Implementation of the Class ClaseBase
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace Seguridad {
	public abstract class ClaseBase {

		private bool m_Activo;
		private int m_Id;
		private string m_Nombre;



		~ClaseBase(){

		}

		public virtual void Dispose(){

		}

		public ClaseBase(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="nombre"></param>
		/// <param name="activo"></param>
		public ClaseBase(int id, string nombre, bool activo = true){

		}

		public bool Activo{
			get{
				return m_Activo;
			}
			set{
				m_Activo = value;
			}
		}

		public int Id{
			get{
				return m_Id;
			}
			set{
				m_Id = value;
			}
		}

		public string Nombre{
			get{
				return m_Nombre;
			}
			set{
				m_Nombre = value;
			}
		}

	}//end ClaseBase

}//end namespace Seguridad