///////////////////////////////////////////////////////////
//  ClaseBase.cs
//  Implementation of the Class ClaseBase
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

using System;

namespace Seguridad {
	public abstract class ClaseBase: IDisposable
    {

        #region Miembros
        private bool m_Activo;
		private long m_Id;
		private string m_Nombre;
        #endregion

        #region Constructores
        ~ClaseBase(){
            Dispose(false);
		}

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

		public virtual void Dispose(bool disposing){
            
		}

	    protected ClaseBase(){

		}

		/// 
		/// <param name="id"></param>
		/// <param name="nombre"></param>
		/// <param name="activo"></param>
		public ClaseBase(long id=0, string nombre = "", bool activo = false)
		{
		    Id = id;
		    Nombre = nombre;
		    Activo = activo;
		}
        #endregion

        #region Metodos
        public bool Activo{
			get{
				return m_Activo;
			}
			set{
				m_Activo = value;
			}
		}

        public long Id
        {
			get{
				return m_Id;
			}
			set{
				m_Id = value;
			}
		}

		public string Nombre{
			get{
				return m_Nombre;
			}
			set{
				m_Nombre = value;
			}
        }
        #endregion
    }//end ClaseBase

}//end namespace Seguridad