///////////////////////////////////////////////////////////
//  clsEventoAuditoria.cs
//  Implementation of the Class clsEventoAuditoria
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using Seguridad;
namespace Seguridad {
	public class clsEventoAuditoria : ClaseBase {

		public Seguridad.clsAuditoria m_clsAuditoria;

        public override string PropiedadIdPadre
        {
            get { return "Fuente.Id"; }
        }
		public clsEventoAuditoria(){

		}

		~clsEventoAuditoria(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsEventoAuditoria

}//end namespace Seguridad