///////////////////////////////////////////////////////////
//  clsPrivilegio.cs
//  Implementation of the Class clsPrivilegio
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using Seguridad;
namespace Seguridad {
	public class clsPrivilegio : ClaseBase {

		private clsPrivilegio m_privilegiopadre;

        public override string PropiedadIdPadre
        {
            get { return "Fuente.Id"; }
        }

		public clsPrivilegio(){

		}

		~clsPrivilegio(){

		}

		public override void Dispose(bool disposing){

		}

		public clsPrivilegio PrivilegioPadre{
			get{
				return m_privilegiopadre;
			}
			set{
				m_privilegiopadre = value;
			}
		}

	}//end clsPrivilegio

}//end namespace Seguridad