///////////////////////////////////////////////////////////
//  clsPrivilegioRol.cs
//  Implementation of the Class clsPrivilegioRol
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace Seguridad {
	public class clsPrivilegioRol : ClaseBase {

		private clsPrivilegio m_privilegio;
		private clsRol m_rol;
		
		public clsPrivilegioRol(){

		}

		~clsPrivilegioRol(){

		}

        public override string PropiedadIdPadre
        {
            get { return "Fuente.Id"; }
        }

		public override void Dispose(bool disposing){

		}

		public clsPrivilegio Privilegio{
			get{
				return m_privilegio;
			}
			set{
				m_privilegio = value;
			}
		}

		public clsRol Rol{
			get{
				return m_rol;
			}
			set{
				m_rol = value;
			}
		}

	}//end clsPrivilegioRol

}//end namespace Seguridad