///////////////////////////////////////////////////////////
//  clsRol.cs
//  Implementation of the Class clsRol
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:40 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad {
	public class clsRol : ClaseBase {

		public clsUsuario m_clsUsuario;

        public override string PropiedadIdPadre
        {
            get { return null; }
        }

		public clsRol(){

		}

		~clsRol(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsRol

}//end namespace Seguridad