///////////////////////////////////////////////////////////
//  clsUsuario.cs
//  Implementation of the Class clsUsuario
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:41 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad {
	public class clsUsuario : ClaseBase {

		public string m_clave;
		public clsRol m_rol;
		public string m_usuario;

		public clsUsuario(){

		}

		~clsUsuario(){

		}

		public override void Dispose(){

		}

		public string Clave{
			get{
				return m_clave;
			}
			set{
				m_clave = value;
			}
		}

		public clsRol Rol{
			get{
				return m_rol;
			}
			set{
				m_rol = value;
			}
		}

		public string Usuario{
			get{
				return m_usuario;
			}
			set{
				m_usuario = value;
			}
		}

	}//end clsUsuario

}//end namespace Seguridad