///////////////////////////////////////////////////////////
//  clsUsuario.cs
//  Implementation of the Class clsUsuario
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:02:41 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


using System;

namespace Seguridad {
	public class clsUsuario : ClaseBase, IDisposable
    {

        #region Miembros
        public string m_clave;
		public clsRol m_rol;
		public string m_usuario;
        public string m_apellido;
        public string m_identificacion;
        public string m_correo;
        public bool m_admin;
        #endregion

        #region Constructores

        public override string PropiedadIdPadre
        {
            get { return "Rol.Id"; }
        }

        public clsUsuario(long id = 0, string nombre = "", bool activo = true) : base(id,nombre,activo)
        {
           
        }

        public clsUsuario()
        {
            Id = 0;
            Nombre = "";
            Activo = false;
        }

	    ~clsUsuario(){
            Dispose(false);
		}

		public override void Dispose(bool disposing){
            if (disposing)
            {
                // Liberar recursos manejados
                Rol.Dispose();
            }
            //Liberar recursos no manejados
		}
        #endregion

        #region Metodos
        public string Clave{
			get{
				return m_clave;
			}
			set{
				m_clave = value;
			}
		}
		public clsRol Rol{
			get{
				return m_rol;
			}
			set{
				m_rol = value;
			}
		}
		public string Usuario{
			get{
				return m_usuario;
			}
			set{
				m_usuario = value;
			}
        }
        public string Identificacion
        {
            get
            {
                return m_identificacion;
            }
            set
            {
                m_identificacion = value;
            }
        }
        public string Apellido
        {
            get
            {
                return m_apellido;
            }
            set
            {
                m_apellido = value;
            }
        }
        public string Correo
        {
            get
            {
                return m_correo;
            }
            set
            {
                m_correo = value;
            }
        }
        public bool Admin
        {
            get
            {
                return m_admin;
            }
            set
            {
                m_admin = value;
            }
        }
        #endregion

    }//end clsUsuario

}//end namespace Seguridad