///////////////////////////////////////////////////////////
//  clsAuditoriaDALC.cs
//  Implementation of the Class clsAuditoriaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:30 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad.DALC {
	internal class clsAuditoriaDALC : Entidad<clsAuditoria> {

		public clsFachadaSeguridad m_clsFachadaSeguridad;

		public clsAuditoriaDALC(){

		}

		~clsAuditoriaDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
        public override int Editar(clsAuditoria obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        public override int Eliminar(clsAuditoria obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        public override int Insertar(clsAuditoria obj)
        {

			return 0;
		}

	}//end clsAuditoriaDALC

}//end namespace DALC