///////////////////////////////////////////////////////////
//  clsEventoAuditoriaDALC.cs
//  Implementation of the Class clsEventoAuditoriaDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using Seguridad.DALC;
namespace Seguridad.DALC {
	internal class clsEventoAuditoriaDALC : Entidad<clsEventoAuditoria> {

		public Seguridad.DALC.clsFachadaClaseBasica m_clsFachadaClaseBasica;

		public clsEventoAuditoriaDALC(){

		}

		~clsEventoAuditoriaDALC(){

		}

		public override void Dispose(){

		}

	}//end clsEventoAuditoriaDALC

}//end namespace DALC