///////////////////////////////////////////////////////////
//  clsFachadaSeguridad.cs
//  Implementation of the Class clsFachadaSeguridad
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace Seguridad.DALC {
	public class clsFachadaSeguridad {

		private clsAuditoriaDALC m_clsAuditoriaDALC;
		private BaseDatos.Comandos m_ejecutor_base_datos;

		public clsFachadaSeguridad(){

		}

		~clsFachadaSeguridad(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Id"></param>
		public Seguridad.clsAuditoria ConsultarAuditoria(int Id){

			return null;
		}

		public List<clsAuditoria> ConsultarAuditorias(){

			return null;
		}

		/// 
		/// <param name="obj"></param>
		public int EditarAuditoria(clsAuditoria obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		public int EliminarAuditoria(clsAuditoria obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		public int InsertarAuditoria(clsAuditoria obj){

			return 0;
		}

       

	}//end clsFachadaSeguridad

}//end namespace DALC