///////////////////////////////////////////////////////////
//  clsPrivilegioDALC.cs
//  Implementation of the Class clsPrivilegioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad.DALC {
	internal class clsPrivilegioDALC : Entidad<clsPrivilegio> {

		public clsFachadaClaseBasica m_clsFachadaClaseBasica;

		public clsPrivilegioDALC(){

		}

		~clsPrivilegioDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
		internal override int Editar(clsPrivilegio obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Eliminar(clsPrivilegio obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Insertar(clsPrivilegio obj){

			return 0;
		}

	}//end clsPrivilegioDALC

}//end namespace DALC