///////////////////////////////////////////////////////////
//  clsPrivilegioRolDALC.cs
//  Implementation of the Class clsPrivilegioRolDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////




using Seguridad.DALC;
namespace Seguridad.DALC {
	internal class clsPrivilegioRolDALC : Entidad<clsPrivilegioRol> {

		public Seguridad.DALC.clsFachadaClaseBase m_clsFachadaClaseBase;

		public clsPrivilegioRolDALC(){

		}

		~clsPrivilegioRolDALC(){

		}

		public override void Dispose(bool disposing){

		}

		/// 
		/// <param name="obj"></param>
		internal override int Editar(clsPrivilegioRol obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Eliminar(clsPrivilegioRol obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Insertar(clsPrivilegioRol obj){

			return 0;
		}

	}//end clsPrivilegioRolDALC

}//end namespace DALC