///////////////////////////////////////////////////////////
//  clsRolDALC.cs
//  Implementation of the Class clsRolDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad.DALC {
	internal class clsRolDALC : Entidad<clsRol> {

		public Seguridad.DALC.clsControladorClaseBasica m_clsControladorClaseBasica;

		public clsRolDALC(){

		}

		~clsRolDALC(){

		}

		public override void Dispose(){

		}

	}//end clsRolDALC

}//end namespace DALC