///////////////////////////////////////////////////////////
//  clsRolDALC.cs
//  Implementation of the Class clsRolDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////


namespace Seguridad.DALC {
	internal class clsRolDALC : Entidad<clsRol> {

		public clsFachadaClaseBase m_clsFachadaClaseBase;

        public clsRolDALC(BaseDatos.Comandos ejecutorBaseDatos, string nombreParametroIdPadre)
            : base(ejecutorBaseDatos, nombreParametroIdPadre)
        {

		}

		~clsRolDALC(){

		}

		public override void Dispose(bool disposing){

		}

	}//end clsRolDALC

}//end namespace DALC