///////////////////////////////////////////////////////////
//  clsUsuarioDALC.cs
//  Implementation of the Class clsUsuarioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace Seguridad.DALC {
	internal class clsUsuarioDALC : Entidad<ClsUsuario> {

		public clsFachadaClaseBasica m_clsFachadaClaseBasica;

		public clsUsuarioDALC(){

		}

		~clsUsuarioDALC(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="obj"></param>
		internal override int Editar(ClsUsuario obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Eliminar(ClsUsuario obj){

			return 0;
		}

		/// 
		/// <param name="obj"></param>
		internal override int Insertar(ClsUsuario obj){

			return 0;
		}

        

	}//end clsUsuarioDALC

}//end namespace DALC