///////////////////////////////////////////////////////////
//  clsUsuarioDALC.cs
//  Implementation of the Class clsUsuarioDALC
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

namespace Seguridad.DALC {
    internal class clsUsuarioDALC : Entidad<clsUsuario>
    {
        public clsUsuarioDALC(BaseDatos.Comandos ejecutorBaseDatos)
        {
            EjecutorBaseDatos = ejecutorBaseDatos;
        }

		~clsUsuarioDALC(){

		}

		public override void Dispose(bool disposing){

		}
       
        /// 
		/// <param name="obj"></param>
        public override int Editar(clsUsuario obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        public override int Eliminar(clsUsuario obj)
        {

			return 0;
		}

		/// 
		/// <param name="obj"></param>
        public override int Insertar(clsUsuario obj)
        {

			return 0;
		}

        

	}//end clsUsuarioDALC

}//end namespace DALC