///////////////////////////////////////////////////////////
//  Entidad.cs
//  Implementation of the Class Entidad
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Data;
using System.Reflection;
using BaseDatos;

namespace Seguridad.DALC {


    internal abstract class Entidad<T> where T : ClaseBase, new()
    {
		private Comandos m_ejecutor_base_datos;
        private string m_nombre_procedimiento;
        protected string m_nombreParametroIdPadre;

		~Entidad(){
            Dispose(false);
		}

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        public virtual void Dispose(bool disposing)
        {

        }

		/// 
		/// <param name="ejecutorBaseDatos"></param>
		public  Entidad(Comandos ejecutorBaseDatos){

		}

		public Entidad(){

		}

		/// 
		/// <param name="Id"></param>
        public virtual T Consultar(int id)
        {

			return null;
		}

        /// 
        /// <param name="fab"></param>
        public List<T> ConsultarTodos(IFabricaEntidad<T> fab)
        {
            DataTable datos;
            EjecutorBaseDatos.limpiarParametros();
            datos = EjecutorBaseDatos.ejecutarProcedimiento(NombreProcedimiento).Tables[0];
            return fab.CrearObjetos(ref datos);
        }

		/// 
		/// <param name="obj"></param>
        public virtual int Editar(T obj)
        {
            int resultado;
            EjecutorBaseDatos.limpiarParametros();
            EjecutorBaseDatos.agregarParametro("id", obj.Id);
            EjecutorBaseDatos.agregarParametro("nombre", obj.Nombre);
            EjecutorBaseDatos.agregarParametro("activo", obj.Activo);
            AsignarValorParametroPadre(obj);
            EjecutorBaseDatos.agregarParametro("opcion", 3);
            resultado = EjecutorBaseDatos.ejecutarProcedimientoNQ(NombreProcedimiento);
            return resultado;
		}

		public Comandos EjecutorBaseDatos{
			get{
				return m_ejecutor_base_datos;
			}
			set{
				m_ejecutor_base_datos = value;
			}
		}

		/// 
		/// <param name="obj"></param>
        public virtual int Eliminar(T obj)
        {
            int resultado;
            EjecutorBaseDatos.limpiarParametros();
            EjecutorBaseDatos.agregarParametro("id", obj.Id);
            EjecutorBaseDatos.agregarParametro("opcion", 4);
            resultado = EjecutorBaseDatos.ejecutarProcedimientoNQ(NombreProcedimiento);
            return resultado;
		}

		/// 
		/// <param name="obj"></param>
        public virtual int Insertar(T obj)
        {
            int resultado;
            EjecutorBaseDatos.limpiarParametros();
            EjecutorBaseDatos.agregarParametro("nombre", obj.Nombre);
            EjecutorBaseDatos.agregarParametro("activo", obj.Activo);
            AsignarValorParametroPadre(obj);
            EjecutorBaseDatos.agregarParametro("opcion", 2);
            resultado = EjecutorBaseDatos.ejecutarProcedimientoNQ(NombreProcedimiento);
            return resultado;
		}

		public string NombreProcedimiento{
			get{
				return m_nombre_procedimiento;
			}
			set{
				m_nombre_procedimiento = value;
			}
		}

        public virtual List<T> ConsultarPorParametros(Dictionary<string, string> parametros, IFabricaEntidad<T> fabrica)
        {
	        DataTable datos;
	        EjecutorBaseDatos.limpiarParametros();
            foreach (var parametro in parametros)
                EjecutorBaseDatos.agregarParametro(parametro.Key, parametro.Value);
	        EjecutorBaseDatos.agregarParametroCursor();
	        datos = EjecutorBaseDatos.ejecutarProcedimiento(NombreProcedimiento).Tables[0];
            return fabrica.CrearObjetos(ref datos);
        }

        protected Entidad(Comandos ejecutorBaseDatos, string nombreParametroIdPadre)
        {
            EjecutorBaseDatos = ejecutorBaseDatos;
            m_nombreParametroIdPadre = nombreParametroIdPadre;
        }

        protected void AsignarValorParametroPadre(ClaseBase obj)
        {
            if (((EjecutorBaseDatos != null) && (m_nombreParametroIdPadre != null) && (obj.PropiedadIdPadre != null)))
            {
                string nombrePropiedad = obj.PropiedadIdPadre;
                object obj1 = null;
                obj1 = obj;
                Type t = obj.GetType();
                PropertyInfo valor = t.GetProperty(nombrePropiedad);
                int indpunto = nombrePropiedad.IndexOf(".",StringComparison.Ordinal);
                while ((indpunto != -1))
                {
                    string tipo = nombrePropiedad.Substring(0, indpunto);
                    t = obj1.GetType();
                    valor = t.GetProperty(tipo);
                    obj1 = valor.GetValue(obj1, null);
                    t = t.GetProperty(tipo).PropertyType;
                    nombrePropiedad = nombrePropiedad.Substring(indpunto + 1);
                    valor = t.GetProperty(nombrePropiedad);
                    indpunto = nombrePropiedad.IndexOf(".", StringComparison.Ordinal);
                }
                if ((valor != null & (obj1 != null)))
                {
                    EjecutorBaseDatos.agregarParametro(m_nombreParametroIdPadre, valor.GetValue(obj1, null));
                }
            }
        }

        public bool TienePermiso(string permiso, string valor, string usuario)
        {
            int resultado;
            EjecutorBaseDatos.limpiarParametros();
            EjecutorBaseDatos.agregarParametro("permiso", permiso);
            EjecutorBaseDatos.agregarParametro("valor", valor);
            EjecutorBaseDatos.agregarParametro("id", valor);
            EjecutorBaseDatos.agregarParametro("opcion", enuTipoAccionBaseDatos.Permiso);
            resultado = EjecutorBaseDatos.ejecutarProcedimientoNQ(NombreProcedimiento);
            if (resultado > 0)
                return true;
            return false;
        }

	}//end Entidad

}//end namespace DALC