///////////////////////////////////////////////////////////
//  clsControladorClaseBasica.cs
//  Implementation of the Class clsControladorClaseBasica
//  Generated by Enterprise Architect
//  Created on:      05-abr-2013 12:08:31 p.m.
//  Original author: kenchic
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace Seguridad.DALC
{
    public interface IConstructorEntidad<T> where T : ClaseBase, new()
    {
        /// <param name="tabla">DataTable que contiene los registros que se van a crear como objetos tipo T.</param>
        List<T> CrearObjetos(ref System.Data.DataTable tabla);

    }
    // IFabricaEntidad

}
// DALC

